#version: "3.8"

services:
  ca:
    build: ./vc-ca
    container_name: vc-ca
    ports:
      - "8000:8000"
    volumes:
      - ./data/keys:/app/keys
    restart: always

  verifier:
    build: ./verifier-site
    container_name: verifier-site
    ports:
      - "5000:5000"
    depends_on:
      - ca
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./circuits/age_checkV1/verification_key.json:/app/verification_key.json:ro
      - ./circuits/age_checkV2:/app/circuits_v2:ro

#  circom:
#    build:
#      context: .
#      dockerfile: circom/Dockerfile
#    container_name: circom-setup
#    volumes:
#      - ./circuits/age_checkV2:/output
#    profiles:
#      - setup
